const fs = require('fs');
let content = fs.readFileSync('./server/data.ts', 'utf-8');

const regex = /\.\.\.Array\.from\(\{\s+length:\s+18\s+\}\)\.map\(\([^)]+\)\s+=>\s+\(\{[\s\S]*?\}\)\)/;

const newLabs = \
  { id: 4, titleEn: 'Advanced LVM: Snapshots and Thin Provisioning', titleFr: 'LVM Avancé : Snapshots et Provisionnement Fin', descriptionEn: 'Master logical volume snapshots and thin pools', descriptionFr: 'Maîtrisez les snapshots et pools fins', difficulty: 'hard', estimatedDuration: 60, objectivesEn: 'Create snapshots, restore data, thin pooling', objectivesFr: 'Créer snapshots, restaurer, thin pooling', order: 4, chapterId: 3 },
  { id: 5, titleEn: 'Managing Systemd Services', titleFr: 'Gestion des services Systemd', descriptionEn: 'Control and monitor system services and timers', descriptionFr: 'Contrôler et surveiller les services et timers système', difficulty: 'medium', estimatedDuration: 40, objectivesEn: 'Start, stop, enable services, create timers', objectivesFr: 'Démarrer, arrêter, activer services, timers', order: 5, chapterId: 8 },
  { id: 6, titleEn: 'Network Configuration with nmcli', titleFr: 'Configuration réseau avec nmcli', descriptionEn: 'Configure IPv4/IPv6 statically and dynamically', descriptionFr: 'Configurer IPv4/IPv6 statique et dynamique', difficulty: 'medium', estimatedDuration: 45, objectivesEn: 'Configure connections, bonding, teaming', objectivesFr: 'Configurer connexions, agrégation, teaming', order: 6, chapterId: 6 },
  { id: 7, titleEn: 'Firewalld Rules and Zones', titleFr: 'Règles et zones Firewalld', descriptionEn: 'Implement network security via zones and rich rules', descriptionFr: 'Implémenter la sécurité réseau via zones et règles riches', difficulty: 'hard', estimatedDuration: 50, objectivesEn: 'Manage zones, add ports/services, rich rules', objectivesFr: 'Gérer zones, ajouter ports, règles riches', order: 7, chapterId: 10 },
  { id: 8, titleEn: 'SELinux Contexts and Policies', titleFr: 'Contextes et politiques SELinux', descriptionEn: 'Troubleshoot and fix SELinux denials', descriptionFr: 'Dépanner et corriger les refus SELinux', difficulty: 'hard', estimatedDuration: 55, objectivesEn: 'Change contexts, manage booleans, audit2allow', objectivesFr: 'Changer contextes, gérer booléens, audit2allow', order: 8, chapterId: 5 },
  { id: 9, titleEn: 'Podman Container Management', titleFr: 'Gestion de conteneurs Podman', descriptionEn: 'Run, manage, and persist containers', descriptionFr: 'Exécuter, gérer et persister des conteneurs', difficulty: 'medium', estimatedDuration: 45, objectivesEn: 'Run containers, map storage, systemd integration', objectivesFr: 'Exécuter, lier stockage, intégration systemd', order: 9, chapterId: 12 },
  { id: 10, titleEn: 'Advanced Container Storage and Networking', titleFr: 'Stockage et réseau conteneurs', descriptionEn: 'Map users, configure container networks', descriptionFr: 'Lier utilisateurs, configurer réseaux', difficulty: 'hard', estimatedDuration: 60, objectivesEn: 'Rootless containers, port mapping, custom nets', objectivesFr: 'Sans racine, mappage ports, réseaux', order: 10, chapterId: 12 },
  { id: 11, titleEn: 'Storage: Stratis Management', titleFr: 'Stockage : Gestion de Stratis', descriptionEn: 'Create and manage Stratis volumes', descriptionFr: 'Créer et gérer des volumes Stratis', difficulty: 'medium', estimatedDuration: 35, objectivesEn: 'Pool creation, file system creation', objectivesFr: 'Créer pool, créer système de fichiers', order: 11, chapterId: 3 },
  { id: 12, titleEn: 'Storage: VDO Configuration', titleFr: 'Stockage : Configuration VDO', descriptionEn: 'Implement Virtual Data Optimizer', descriptionFr: 'Implémenter Virtual Data Optimizer (VDO)', difficulty: 'medium', estimatedDuration: 40, objectivesEn: 'Configure VDO, compression, deduplication', objectivesFr: 'Configurer VDO, compression, déduplication', order: 12, chapterId: 3 },
  { id: 13, titleEn: 'Automated Job Scheduling', titleFr: 'Planification automatisée des tâches', descriptionEn: 'Use cron and at for task automation', descriptionFr: 'Utiliser cron et at pour automatiser', difficulty: 'easy', estimatedDuration: 30, objectivesEn: 'Crontab usage, systemd timers', objectivesFr: 'Utilisation crontab, timers systemd', order: 13, chapterId: 8 },
  { id: 14, titleEn: 'Package Management with DNF', titleFr: 'Gestion des paquets avec DNF', descriptionEn: 'Install software and manage modules', descriptionFr: 'Installer des logiciels et modules', difficulty: 'easy', estimatedDuration: 30, objectivesEn: 'AppStream modules, package history', objectivesFr: 'Modules AppStream, historique', order: 14, chapterId: 7 },
  { id: 15, titleEn: 'Monitoring System Performance', titleFr: 'Surveillance des performances', descriptionEn: 'Analyze CPU, Memory and I/O usage', descriptionFr: 'Analyser CPU, mémoire et E/S', difficulty: 'medium', estimatedDuration: 40, objectivesEn: 'vmstat, iostat, sar, top usage', objectivesFr: 'Utilisation vmstat, iostat, sar, top', order: 15, chapterId: 9 },
  { id: 16, titleEn: 'Managing System Logs', titleFr: 'Gestion des journaux système', descriptionEn: 'Configure rsyslog and query journald', descriptionFr: 'Configurer rsyslog et journald', difficulty: 'medium', estimatedDuration: 35, objectivesEn: 'Filter journalctl, persistent logs', objectivesFr: 'Filtrer journalctl, logs persistants', order: 16, chapterId: 9 },
  { id: 17, titleEn: 'SSH Key-based Authentication', titleFr: 'Authentification SSH par clé', descriptionEn: 'Secure remote access with keys', descriptionFr: 'Sécuriser l accès distant avec des clés', difficulty: 'easy', estimatedDuration: 25, objectivesEn: 'Generate keys, ssh-copy-id, disable password login', objectivesFr: 'Générer clés, copier, désactiver mdp', order: 17, chapterId: 5 },
  { id: 18, titleEn: 'Boot Process and GRUB2', titleFr: 'Processus de démarrage et GRUB2', descriptionEn: 'Troubleshoot boot issues and reset passwords', descriptionFr: 'Dépanner le démarrage et réinitialiser mdp', difficulty: 'hard', estimatedDuration: 55, objectivesEn: 'Break boot sequence, reset root password', objectivesFr: 'Interrompre boot, réinitialiser root', order: 18, chapterId: 8 },
  { id: 19, titleEn: 'User ACLs and Special Permissions', titleFr: 'ACLs et permissions spéciales', descriptionEn: 'Advanced file access control', descriptionFr: 'Contrôle d accès avancé', difficulty: 'medium', estimatedDuration: 35, objectivesEn: 'setfacl, getfacl, SGID on directories', objectivesFr: 'setfacl, getfacl, SGID sur répertoires', order: 19, chapterId: 4 },
  { id: 20, titleEn: 'Configuring Time Sync (Chrony)', titleFr: 'Configuration de synchronisation (Chrony)', descriptionEn: 'Manage NTP settings using chronyd', descriptionFr: 'Gérer NTP avec chronyd', difficulty: 'easy', estimatedDuration: 20, objectivesEn: 'Set timezone, configure peers', objectivesFr: 'Définir fuseau, configurer pairs', order: 20, chapterId: 6 },
  { id: 21, titleEn: 'RHCSA Comprehensive Mock Exam Lab', titleFr: 'Examen blanc RHCSA Complet', descriptionEn: 'A full-scale practice merging all topics', descriptionFr: 'Pratique complète sur l ensemble', difficulty: 'hard', estimatedDuration: 150, objectivesEn: 'Storage, Network, Users, Podman, SELinux', objectivesFr: 'Stockage, Réseau, Utilisateurs, Podman, SELinux', order: 21, chapterId: 10 }
\;

content = content.replace(regex, newLabs);

fs.writeFileSync('./server/data.ts', content);
console.log('Fixed labs');
