CREATE TYPE "public"."difficulty" AS ENUM('beginner', 'intermediate', 'advanced', 'easy', 'medium', 'hard');--> statement-breakpoint
CREATE TYPE "public"."role" AS ENUM('user', 'admin');--> statement-breakpoint
CREATE TABLE "chapters" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chapters_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"chapterNumber" integer NOT NULL,
	"titleEn" varchar(255) NOT NULL,
	"titleFr" varchar(255) NOT NULL,
	"descriptionEn" text,
	"descriptionFr" text,
	"contentEn" text,
	"contentFr" text,
	"order" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "chapters_chapterNumber_unique" UNIQUE("chapterNumber")
);
--> statement-breakpoint
CREATE TABLE "commands" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "commands_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nameEn" varchar(100) NOT NULL,
	"nameFr" varchar(100) NOT NULL,
	"descriptionEn" text NOT NULL,
	"descriptionFr" text NOT NULL,
	"syntax" varchar(500) NOT NULL,
	"optionsEn" text,
	"optionsFr" text,
	"examplesEn" text,
	"examplesFr" text,
	"outputExample" text,
	"relatedCommands" json,
	"chapterId" integer NOT NULL,
	"difficulty" "difficulty" NOT NULL,
	"order" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "examQuestions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "examQuestions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"examId" integer NOT NULL,
	"questionEn" text NOT NULL,
	"questionFr" text NOT NULL,
	"optionsEn" json NOT NULL,
	"optionsFr" json NOT NULL,
	"correctAnswer" varchar(10) NOT NULL,
	"explanationEn" text,
	"explanationFr" text,
	"difficulty" "difficulty" NOT NULL,
	"order" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "examResults" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "examResults_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"examId" integer NOT NULL,
	"score" numeric(5, 2) NOT NULL,
	"passed" boolean NOT NULL,
	"completedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "exams" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "exams_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"titleEn" varchar(255) NOT NULL,
	"titleFr" varchar(255) NOT NULL,
	"descriptionEn" text,
	"descriptionFr" text,
	"timeLimit" integer NOT NULL,
	"totalQuestions" integer NOT NULL,
	"passingScore" numeric(5, 2) NOT NULL,
	"order" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "labProgress" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "labProgress_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"labId" integer NOT NULL,
	"completedAt" timestamp,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "labs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "labs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"titleEn" varchar(255) NOT NULL,
	"titleFr" varchar(255) NOT NULL,
	"descriptionEn" text,
	"descriptionFr" text,
	"difficulty" "difficulty" NOT NULL,
	"estimatedDuration" integer,
	"objectivesEn" text,
	"objectivesFr" text,
	"prerequisitesEn" text,
	"prerequisitesFr" text,
	"instructionsEn" text,
	"instructionsFr" text,
	"validationEn" text,
	"validationFr" text,
	"solutionEn" text,
	"solutionFr" text,
	"chapterId" integer,
	"order" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "userProgress" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "userProgress_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"chapterId" integer NOT NULL,
	"completedAt" timestamp,
	"progress" numeric(5, 2) DEFAULT '0',
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"openId" varchar(64) NOT NULL,
	"name" text,
	"email" varchar(320),
	"loginMethod" varchar(64),
	"role" "role" DEFAULT 'user' NOT NULL,
	"language" varchar(5) DEFAULT 'en' NOT NULL,
	"theme" varchar(10) DEFAULT 'light' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"lastSignedIn" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_openId_unique" UNIQUE("openId")
);
